### PR TITLE
Update pirates.cfg in zh_CN

### PR DESCRIPTION
**Pull request by dwightkung**
fix some inproper words, add translation to new lines.

### All Submissions:

- [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### Tested Changes:

1. [ ] Have you lint your code (lua lint) locally prior to submission?

### Changes to Core Features:

- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you successfully ran tests with your changes locally?

### Comments
The former request is no longer editable, or I dont know how. 
So I create a new one. 
Let me know if there is a easier way to update files. 
PR:
### Crow‘s nest to observatory, which is easier to understand in chinese.

图片

### Some of the new lines.

图片

### CODE REVIEW

**Comment by danielmartin0** [comment]
@dwightkung Thank-you for the updates and screenshots! Short PRs are a good way to push updates — no need to put this much effort in every time but thank-you.

**Comment by danielmartin0** [comment]
I notice from your screenshot that in the top bar, I'm missing the localisation of 'Fuel' and '/s'. Please let me know any other English text I'm missing config lines for.

**Comment by dwightkung** [comment]
@danielmartin0 ‘/s’ for 'per second', it's widely used in China too. So I think no need to pull another request only for 'fuel', maybe in the next significant update.

**Comment by danielmartin0** [comment]
Ok, cool. Yeah, I do several changes and batch them together unless it's urgent. Next update might be quite a while also.

**Comment by dwightkung** [comment]
Some missing lines:
When a crew have no name
屏幕截图(560)
The place selling another hold
屏幕截图(558)
When a boat has only one hold, the translation works. But after we bought another, the first hold turns back to english, and the second was translated well.
屏幕截图(559)

### All above is not urgent, and I will keep updating if I find more.

**Pull request merged**
